version: "3"
services:
    node01:
        build: .
        image: watchdog
        environment:
            - PORT_NUM=8
        ports:
            - "10059:9559"
        cap_add:
            - NET_ADMIN
    node02:
        image: watchdog
        environment:
            - PORT_NUM=8
        ports:
            - "10060:9559"
        cap_add:
            - NET_ADMIN
