version: "3"
services:
    node01:
        build: .
        image: bmv2-switch
        environment:
            - PORT_NUM=8
            - GRPC_PORT=9559
        ports:
            - "9559:9559"
        cap_add:
            - NET_ADMIN
    node02:
        image: bmv2-switch
        environment:
            - PORT_NUM=8
            - GRPC_PORT=9559
        ports:
            - "9559:9559"
        build: .
        cap_add:
            - NET_ADMIN
