Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.provision "file", source: "../docker", destination: "$HOME/"

    config.vm.provision :shell, path: "bootstrap.sh"
end